name = "sdfff-20250910-1253"
compatibility_date = "2025-09-10"
main = "_worker.js"

kv_namespaces = [
  { binding = "KV", id = "8a2d5758957149d0b21252ee7571d3c7" }
]

[vars]
UUID = "5c240cb3-0c29-491a-ad03-32a30aafe25d"


# 可选：环境配置
[env.production]
compatibility_date = "2025-09-10"

[env.staging]
compatibility_date = "2025-09-10"
